# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyMessages' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'MessageKit'

  target 'MyMessagesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyMessagesUITests' do
    # Pods for testing
  end

end
