# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreDataBLETutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreDataBLETutorial
pod 'Charts'
end

 
